name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
        - "**/*.md"
        - "LICENSE"
  
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: ["1.23", "1.24"]
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: download dependencies
        run: |
          go get ./...

      - name: Run lint
        run: make install-tools lint

      - name: Run tests
        run: make test
